#UBUNTU
- name: Install required system packages on Ubuntu
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  
- name: Add Docker GPG apt Key on Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"


- name: Add Docker Repository on Ubuntu 
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce on Ubuntu 
  when: ansible_os_family == "Debian"
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Add user to docker group when Ubuntu
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  become: true
  with_items: "{{ docker_users['ubuntu']['users'] }}"
  when: ansible_os_family == "Debian"

#REDHAT


- name: Adding Docker GPG rpm Key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  when: ansible_os_family == "RedHat" 

- name: Adding Docker Repository
  yum_repository:
    name: docker
    description: docker repository
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_os_family == "RedHat" 

- name: Installing docker yum
  yum:
    name:
      - docker-ce
      - python3
      - python3-pip

    state: latest
    update_cache: true
  when: ansible_os_family == "RedHat" 

# - name: Add signing key
#   ansible.builtin.rpm_key:
#     key: "https://download.docker.com/linux/rhel/gpg"
#     state: present
#   when: ansible_os_family == "RedHat"

# - name: Add repository into repo.d list
#   ansible.builtin.yum_repository:
#     name: docker
#     description: docker repository
#     baseurl: "https://download.docker.com/linux/rhel/$releasever/$basearch/stable"
#     enabled: true
#     gpgcheck: true
#     gpgkey: "https://download.docker.com/linux/rhel/gpg"
#   when: ansible_os_family == "RedHat"

# # - name: Install docker on Red Hat
# #   yum:
# #     name: 
# #       - yum-utils

# #     state: present
# #   when: ansible_os_family == "RedHat"

# - name: Install Docker
#   ansible.builtin.yum:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#     state: latest
#     update_cache: true
#   when: ansible_os_family == "RedHat"

# - name: Add user to docker group when RedHat
#   user:
#     name: "{{ item }}"
#     append: yes
#     groups: docker
#   become: true
#   with_items: "{{ docker_users['redhat']['users'] }}"
#   when: ansible_os_family == "RedHat"

# - name: Install Python 3
#   yum:
#     name: python3
#     state: present

# - name: Install pip
#   yum:
#     name: python3-pip
#     state: latest
#   when: ansible_os_family == "RedHat" 

#GENERAL
  
- name: Install Docker Module for Python
  pip:
    name: docker

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Run Nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image_name }}"
    ports:
      - 8080:80
  become: true



